// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0lqzl-MVPoGMpPckmhrNOr4BDPvB_tq8',
    appId: '1:255005773443:web:e990d393d7b85e34b415b6',
    messagingSenderId: '255005773443',
    projectId: 'mynotes-flutter-9ff73',
    authDomain: 'mynotes-flutter-9ff73.firebaseapp.com',
    storageBucket: 'mynotes-flutter-9ff73.appspot.com',
    measurementId: 'G-R45SYT6CXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJ7kuQH7Lu8ozlSPCvyuMJNA963bo_q8',
    appId: '1:255005773443:android:bba3dd67526885ecb415b6',
    messagingSenderId: '255005773443',
    projectId: 'mynotes-flutter-9ff73',
    storageBucket: 'mynotes-flutter-9ff73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgbcfHDPeyS2ohc5viaqs5sxOwN5QlR4',
    appId: '1:255005773443:ios:4c2cdd5294802641b415b6',
    messagingSenderId: '255005773443',
    projectId: 'mynotes-flutter-9ff73',
    storageBucket: 'mynotes-flutter-9ff73.appspot.com',
    iosClientId: '255005773443-tdupece3n0e49mmmdkb33tc5nrl85lh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.dart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFgbcfHDPeyS2ohc5viaqs5sxOwN5QlR4',
    appId: '1:255005773443:ios:6638910fe84c5d5bb415b6',
    messagingSenderId: '255005773443',
    projectId: 'mynotes-flutter-9ff73',
    storageBucket: 'mynotes-flutter-9ff73.appspot.com',
    iosClientId: '255005773443-br52mu25vj39p6rdkmk16pes3ngv0o1e.apps.googleusercontent.com',
    iosBundleId: 'com.example.dart.RunnerTests',
  );
}
